# Generated by Django 5.2.7 on 2026-02-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('nume_brand', models.CharField(max_length=100, unique=True)),
                ('tara_origine', models.CharField(max_length=100)),
                ('an_infiintare', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nume_categorie', models.CharField(max_length=100)),
                ('gen_tinta', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('U', 'Unisex'), ('C', 'Copii')], max_length=2)),
                ('vizibil_pe_site', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marime',
            fields=[
                ('id_marime', models.AutoField(primary_key=True, serialize=False)),
                ('valoare', models.CharField(max_length=10)),
                ('tip_marime', models.CharField(choices=[('EU', 'European'), ('US', 'American'), ('UK', 'Britanic')], max_length=2)),
                ('pentru_copii', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nume_material', models.CharField(max_length=100)),
                ('este_impermeabil', models.BooleanField(default=False)),
                ('instructiuni_spalare', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id_incaltaminte', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=150)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descriere', models.TextField()),
                ('in_stoc', models.BooleanField(default=True)),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
                ('greutate', models.FloatField(blank=True, null=True)),
                ('culoare_principala', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog_Produse.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog_Produse.categorie')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalog_Produse.material')),
            ],
        ),
        migrations.CreateModel(
            name='StocMarime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField(default=0)),
                ('marime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog_Produse.marime')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog_Produse.produs')),
            ],
            options={
                'unique_together': {('produs', 'marime')},
            },
        ),
        migrations.AddField(
            model_name='produs',
            name='marimi',
            field=models.ManyToManyField(through='Catalog_Produse.StocMarime', to='Catalog_Produse.marime'),
        ),
    ]
