# Generated by Django 5.2.7 on 2026-02-17 13:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('nume_brand', models.CharField(max_length=100, unique=True)),
                ('tara_origine', models.CharField(max_length=100)),
                ('an_infiintare', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nume_categorie', models.CharField(max_length=100)),
                ('gen_tinta', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('U', 'Unisex'), ('C', 'Copii')], max_length=2)),
                ('vizibil_pe_site', models.BooleanField(default=True)),
                ('culoare_cod', models.CharField(default='#004d99', help_text='Cod HEX (ex: #FF0000)', max_length=7)),
                ('icon_fontawesome', models.CharField(default='fa-solid fa-shoe-prints', help_text='Clasa FontAwesome', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marime',
            fields=[
                ('id_marime', models.AutoField(primary_key=True, serialize=False)),
                ('valoare', models.CharField(max_length=10)),
                ('tip_marime', models.CharField(choices=[('EU', 'European'), ('US', 'American'), ('UK', 'Britanic')], max_length=2)),
                ('pentru_copii', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nume_material', models.CharField(max_length=100)),
                ('este_impermeabil', models.BooleanField(default=False)),
                ('instructiuni_spalare', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id_incaltaminte', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=150)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descriere', models.TextField()),
                ('in_stoc', models.BooleanField(default=True)),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
                ('greutate', models.FloatField(blank=True, null=True)),
                ('culoare_principala', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog_Produse.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog_Produse.categorie')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Catalog_Produse.material')),
            ],
        ),
        migrations.CreateModel(
            name='StocMarime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField(default=0)),
                ('marime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog_Produse.marime')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog_Produse.produs')),
            ],
            options={
                'unique_together': {('produs', 'marime')},
            },
        ),
        migrations.AddField(
            model_name='produs',
            name='marimi',
            field=models.ManyToManyField(through='Catalog_Produse.StocMarime', to='Catalog_Produse.marime'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Număr de telefon')),
                ('adresa', models.TextField(blank=True, max_length=255, null=True, verbose_name='Adresă completă')),
                ('judet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Județ')),
                ('data_nasterii', models.DateField(blank=True, null=True, verbose_name='Data nașterii')),
                ('cnp', models.CharField(blank=True, max_length=13, null=True, verbose_name='CNP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
