# Generated by Django 5.2.7 on 2026-02-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog_Produse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='culoare_cod',
            field=models.CharField(default='#004d99', help_text='Cod HEX (ex: #FF0000)', max_length=7),
        ),
        migrations.AddField(
            model_name='categorie',
            name='icon_fontawesome',
            field=models.CharField(default='fa-solid fa-shoe-prints', help_text='Clasa FontAwesome', max_length=50),
        ),
    ]
