# Generated by Django 5.2.7 on 2026-02-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog_Produse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cod Confirmare'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmat',
            field=models.BooleanField(default=False, verbose_name='E-mail Confirmat'),
        ),
    ]
