# Generated by Django 5.2.7 on 2026-02-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog_Produse', '0002_customuser_cod_customuser_email_confirmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizarii', models.DateTimeField(auto_now=True, verbose_name='Data Vizualizării')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog_Produse.produs')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istoric_vizualizari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_vizualizarii'],
            },
        ),
    ]
