# Generated by Django 5.2.7 on 2026-02-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog_Produse', '0003_vizualizare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, verbose_name='Nume Campanie Promoțională')),
                ('data_creare', models.DateTimeField(auto_now_add=True, verbose_name='Data Creării')),
                ('data_expirare', models.DateTimeField(verbose_name='Data Expirării')),
                ('procent_reducere', models.IntegerField(help_text='Ex: 15 pentru 15% reducere', verbose_name='Procent Reducere (%)')),
                ('subiect_email', models.CharField(help_text='Ex: Produsele tale preferate au acum reducere!', max_length=150, verbose_name='Subiect E-mail Promoțional')),
            ],
        ),
    ]
