# Generated by Django 5.2.7 on 2026-02-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog_Produse', '0004_promotie'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotie',
            name='categorii',
            field=models.ManyToManyField(to='Catalog_Produse.categorie', verbose_name='Categorii vizate'),
        ),
        migrations.AddField(
            model_name='promotie',
            name='template_ales',
            field=models.CharField(choices=[('promo_dinamic.txt', 'Template Casual / Sport (Dinamic)'), ('promo_elegant.txt', 'Template Elegant / Premium')], default='promo_dinamic.txt', max_length=50, verbose_name='Fișier Template Text'),
        ),
        migrations.AlterField(
            model_name='promotie',
            name='data_creare',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='promotie',
            name='nume',
            field=models.CharField(max_length=100, verbose_name='Nume Campanie'),
        ),
        migrations.AlterField(
            model_name='promotie',
            name='procent_reducere',
            field=models.IntegerField(verbose_name='Procent Reducere (%)'),
        ),
        migrations.AlterField(
            model_name='promotie',
            name='subiect_email',
            field=models.CharField(max_length=150, verbose_name='Subiect E-mail'),
        ),
    ]
